# Generated by Django 5.1.15 on 2026-09-13 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Goods Received'), ('INSPECTED', 'Inspected'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='ACCEPTED', max_length=20)),
                ('received_date', models.DateField()),
                ('delivery_challan_number', models.CharField(blank=True, default='', max_length=50)),
                ('received_by', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'ap_goods_receipts',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accepted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='goods_receipts.goodsreceipt')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='purchase_orders.poitem')),
            ],
            options={
                'db_table': 'ap_grn_items',
            },
        ),
    ]
