# Generated by Django 5.1.15 on 2026-09-13 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gstin', models.CharField(blank=True, db_index=True, default='', help_text='15-character Indian GSTIN', max_length=15)),
                ('pan', models.CharField(blank=True, default='', help_text='10-character Indian Permanent Account Number', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], db_index=True, default='ACTIVE', max_length=20)),
                ('msme_registered', models.BooleanField(default=False)),
                ('payment_terms_days', models.PositiveIntegerField(default=30, help_text='Standard payment credit period in days')),
            ],
            options={
                'db_table': 'ap_vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(help_text='Plain account number for payments processing', max_length=50)),
                ('ifsc_code', models.CharField(help_text='11-character Indian IFSC code', max_length=11)),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='vendors.vendor')),
            ],
            options={
                'db_table': 'ap_vendor_bank_accounts',
            },
        ),
    ]
