# Generated by Django 5.1.15 on 2026-09-13 15:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMatrixRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Null represents infinity (no upper bound)', max_digits=14, null=True)),
                ('required_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('AP_CLERK', 'Accounts Payable Clerk'), ('APPROVER', 'Department Approver / Manager'), ('FINANCE', 'Finance Manager'), ('CFO', 'Chief Financial Officer'), ('VENDOR', 'Vendor Representative')], max_length=20)),
                ('step_order', models.PositiveIntegerField(default=1, help_text='Order of approval stage (1, 2, 3...)')),
                ('is_parallel', models.BooleanField(default=False, help_text='True if multiple approvers of this role can act concurrently at this stage')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'ap_approval_matrix_rules',
                'ordering': ['min_amount', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('total_steps', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='invoices.invoice')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ap_approval_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('role_acted_as', models.CharField(choices=[('ADMIN', 'Administrator'), ('AP_CLERK', 'Accounts Payable Clerk'), ('APPROVER', 'Department Approver / Manager'), ('FINANCE', 'Finance Manager'), ('CFO', 'Chief Financial Officer'), ('VENDOR', 'Vendor Representative')], max_length=20)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('ESCALATE', 'Escalate')], db_index=True, max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrequest')),
            ],
            options={
                'db_table': 'ap_approval_actions',
                'ordering': ['created_at'],
            },
        ),
    ]
