# Generated by Django 5.1.15 on 2026-09-13 15:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='ISSUED', max_length=30)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('issue_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor')),
            ],
            options={
                'db_table': 'ap_purchase_orders',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('item_code', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(default='NOS', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST % (e.g. 18.00 for 18%)', max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'ap_po_items',
                'ordering': ['line_number'],
            },
        ),
    ]
