# Generated by Django 5.1.15 on 2026-09-13 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods_receipts', '0001_initial'),
        ('invoices', '0001_initial'),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('2_WAY', '2-Way Match (PO <-> Invoice)'), ('3_WAY', '3-Way Match (PO <-> GRN <-> Invoice)')], default='3_WAY', max_length=20)),
                ('status', models.CharField(choices=[('MATCHED', 'Fully Matched'), ('PARTIAL_MATCH', 'Partial Match within Tolerance'), ('MISMATCH', 'Mismatch / Exception')], default='MISMATCH', max_length=20)),
                ('is_successful', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('discrepancies', models.JSONField(blank=True, default=list, help_text='List of variance details')),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods_receipts.goodsreceipt')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_runs', to='invoices.invoice')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'ap_match_runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
