# Generated by Django 5.1.15 on 2026-09-13 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_system', models.CharField(default='GenericERP', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Sync'), ('SUCCESS', 'Successfully Synced'), ('FAILED', 'Sync Failed')], default='PENDING', max_length=20)),
                ('erp_document_number', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_syncs', to='invoices.invoice')),
            ],
            options={
                'db_table': 'ap_erp_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
