# Generated by Django 5.1.15 on 2026-09-13 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=100)),
                ('rule_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], db_index=True, default='PASSED', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='invoices.invoice')),
            ],
            options={
                'db_table': 'ap_validation_results',
                'ordering': ['created_at'],
            },
        ),
    ]
