# Generated by Django 5.1.15 on 2026-09-13 15:14

import apps.invoices.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods_receipts', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.invoices.models.invoice_file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('pages_count', models.PositiveIntegerField(default=1)),
                ('vendor_name_extracted', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_gstin_extracted', models.CharField(blank=True, default='', max_length=20)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('fiscal_year', models.CharField(blank=True, db_index=True, default='', help_text='Fiscal year, e.g., FY2026-27', max_length=20)),
                ('invoice_date', models.DateField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('OCR_PROCESSING', 'OCR In Progress'), ('OCR_COMPLETED', 'OCR Completed'), ('VALIDATING', 'Validating'), ('READY_FOR_MATCHING', 'Ready for PO Matching'), ('EXCEPTION', 'Exception / Attention Required'), ('READY_FOR_APPROVAL', 'Ready for Approval'), ('APPROVED', 'Approved'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='UPLOADED', max_length=30)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Extracted'), ('PARTIAL', 'Partially Extracted'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('matching_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending'), ('MATCHED_2WAY', '2-Way Matched'), ('MATCHED_3WAY', '3-Way Matched'), ('MISMATCH_EXCEPTION', 'Mismatch Exception')], db_index=True, default='PENDING', max_length=30)),
                ('approval_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], db_index=True, default='NOT_SUBMITTED', max_length=20)),
                ('payment_status', models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Payment Requested'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_REQUESTED', max_length=20)),
                ('ocr_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregated OCR extraction confidence percentage', max_digits=5)),
                ('raw_ocr_text', models.TextField(blank=True, default='')),
                ('raw_ocr_data', models.JSONField(blank=True, default=dict, help_text='Structured OCR output with per-field confidence')),
                ('notes', models.TextField(blank=True, default='')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchase_orders.purchaseorder')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='vendors.vendor')),
            ],
            options={
                'db_table': 'ap_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('hsn_sac_code', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(default='NOS', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('95.00'), max_digits=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('matched_grn_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_invoice_items', to='goods_receipts.grnitem')),
                ('matched_po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_invoice_items', to='purchase_orders.poitem')),
            ],
            options={
                'db_table': 'ap_invoice_items',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor__isnull', False), models.Q(('invoice_number', ''), _negated=True), models.Q(('fiscal_year', ''), _negated=True)), fields=('vendor', 'invoice_number', 'fiscal_year'), name='unique_vendor_invoice_fiscal_year'),
        ),
    ]
