# Generated by Django 5.1.15 on 2026-09-13 15:25

import apps.invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='content_type',
            field=models.CharField(blank=True, default='application/pdf', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.invoices.models.invoice_file_upload_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
