# Generated by Django 5.1.15 on 2026-09-13 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('ACH', 'ACH / Wire')], default='NEFT', max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Payment Requested'), ('PROCESSING', 'Processing with Bank'), ('PAID', 'Payment Settled / Paid'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=20)),
                ('reference_number', models.CharField(blank=True, db_index=True, default='', help_text='Bank UTR Number or Transaction Ref', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bank_response_payload', models.JSONField(blank=True, default=dict)),
                ('advice_notes', models.TextField(blank=True, default='')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.invoice')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='vendors.vendor')),
            ],
            options={
                'db_table': 'ap_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
